services:
  db:
    image: postgres:17-bookworm
    container_name: duepublico-postgres
    restart: always
    # set shared memory limit when using docker-compose
    #
    # Docker's Default Shared Memory Limit: Docker containers come with a default shared memory limit of 64MB, which often isn't enough for PostgreSQL.
    #
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
  web:
    image: duepublico-war:latest
    depends_on:
      - db
    container_name: 'duepublico-war'
    ports:
      - "8092:8080"
    deploy:
      resources:
        limits:
          memory: "2g"
    restart: always
    volumes:
      - ../../duepublico-webapp/target/duepublico-webapp-2.0-SNAPSHOT.war:/usr/local/tomcat/webapps/duepublico.war
    links:
      - db
