# XML templates for common webpage sections 
MCR.URIResolver.xslIncludes.MyCoReWebPage=%MCR.URIResolver.xslIncludes.MyCoReWebPage%,duepublico-webpage-utils.xsl

######################################################################
#                                                                    #
#                        Predefined Exports                          #
#                                                                    #
#     https://duepublico2.uni-due.de/rsc/export-list/<UUID>          #
#                                                                    #
######################################################################

MCR.Jersey.Resource.Packages=%MCR.Jersey.Resource.Packages%,unidue.ub.duepublico.resources

DuEPublico.PredefinedExport.DefaultSOLRURI=solr:requestHandler:export:rows=9999&sort=mods.dateIssued+desc

# UNIKATE
DuEPublico.PredefinedExport.55636fc4-f95f-499a-9172-1ad919280ce7.URI=%DuEPublico.PredefinedExport.DefaultSOLRURI%&q=root%3Aduepublico_mods_00023613&q.op=OR&indent=true&fl=mods.pindexname
DuEPublico.PredefinedExport.f347c923-dffa-4368-8b55-5d3ff25d9021.URI=solr:requestHandler:select:q=root%3Aduepublico_mods_00023613&rows=0&wt=json&facet=true&facet.sort=index&facet.limit=-1&facet.field=facet.name&facet.field=facet.subject
